#!/bin/bash

set -e

usage()  {
    echo "Usage: $(basename "$0") [-d DOMAIN] [-o OUTPUT] [-t] SOURCE_DIR"
    echo
    echo "  -d  The text domain to use. Defaults to source directory basename"
    echo "  -o  The output directory. Defaults to SOURCE_DIR/languages"
    echo "  -t  Drop the text domain in po file names for in-theme translations"
    exit
}

theme=0
while getopts ":d:o:t" o; do
    case "${o}" in
        d)
            domain=${OPTARG}
            ;;
        o)
            output=${OPTARG%/}
            ;;
        t)
            theme=1
            ;;
        *)
            usage
            ;;
    esac
done
shift $((OPTIND - 1))

test -z "$1" && usage

source="${1%/}"
domain=${domain:-$(basename "$source")}

output=${output:-"$source/languages"}
pot="$output/$domain.pot"

pobase="$(test $theme = 1 && printf "%s/" "$output" || printf "%s/%s-" "$output" "$domain")"

echo "source: $source"
echo "pot:    $pot"
echo "po:     $pobase*.po"

# update POT from source
composer exec -- wp i18n make-pot --headers='{"POT-Creation-Date":null}' --skip-js --file-comment="" --headers='{"POT-Creation-Date":"GIT"}' "$source" "$pot"

# drop headers from POT
sed -Ei '/"(Report-Msgid-Bugs-To|Last-Translator|Language-Team|POT-Creation-Date|PO-Revision-Date): /d' "$pot"

# update PO from POT and compile MO
for pofile in "$pobase"*.po; do
    test ! -f "$pofile" && continue
    msgmerge --previous -U "$pofile" "$pot"
    msgfmt --use-fuzzy "$pofile" -o "${pofile%.po}.mo"
done
